name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build with Parcel
        run: npm run build

      - name: Zip dist Folder
        run: zip -r dist.zip dist

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.zip
